Adding a test plan for QUARKUS-478.
quarkus-qe/quarkus-test-plans pull request #20
Opened 2021-03-25 23:26 UTC by mjurc

2021-03-26 09:02 UTC, rsvoboda requested changes

2021-03-26 09:02 UTC, rsvoboda commented on QUARKUS-478.md
> +## Scope of the testing
I think `quarkus.openshift.jvm-dockerfile=MyDockerFile` and native equivalent should be also covered

2021-03-26 09:02 UTC, rsvoboda commented on QUARKUS-478.md
> +  - Test with invalid dockerfiles
We checked 
 - corrupted Dockerfile - invalid directory name
 - empty Dockerfile

and `dockerfiles` => `Dockerfiles`

2021-05-06 13:36 UTC, rsvoboda commented
@mjurc will you update the PR anytime soon?

2021-05-06 22:34 UTC, mjurc commented
@rsvoboda Done!

2021-05-07 07:18 UTC, rsvoboda approved these changes

2021-05-07 07:19 UTC, merged