Test plan for Quarkus-959
quarkus-qe/quarkus-test-plans pull request #27
Opened 2021-07-06 11:31 UTC by pjgg

2021-07-08 14:10 UTC, rsvoboda commented
Please update the PR to comply with https://gitlab.cee.redhat.com/quarkus-qe/signpost/-/blob/main/pull-requests.md#main-rule-set-for-pull-requests

2021-07-09 12:24 UTC, rsvoboda requested changes
Also miss some details like:

 - Extend CRUD test cases with applications that spin up the database dev services
 - Extend messaging test cases with applications that spin up messaging dev services
 - Use the existing dev mode test coverage to ensure that running scenarios without dev services is still possible 
 - Cover DEV UI
 - Quarkus app is waiting for the necessary services to start, is developer informed about started services progress?

2021-07-12 16:41 UTC, pjgg commented on QUARKUS-959.md
> + - All persisted databases which we have extensions (Postgresql, MariaDB, Mysql, Oracle, DB2)
Yes, I've removed both databases from the test plan. We could extend it in the future once will be supported.

2021-07-12 16:44 UTC, pjgg commented on QUARKUS-959.md
> + - Some messaging extensions such as AMQP, Strimzi Kafka, RedPanda Kafka
Strimzi Kafka looks that is not ready, so lets remove it from now and we could add it in the future.

2021-07-12 16:46 UTC, pjgg commented on QUARKUS-959.md
> + - Ensure this coverage works both in JVM and NATIVE mode
I've covered this subject with the following point:

```
A developer must be able to run test with dev-services enabled and also run the same service in dev mode. Both services (test + dev-services and quarkus dev-mode + dev-services) must be not interfere with each other.
```

Let me know If I am missing something else, please.

2021-07-12 16:51 UTC, pjgg commented on QUARKUS-959.md
> + - Make sure the service is started just once and not respinned multiple times
covered by the following point:

```
Developers must be able to develop his services following a continuos testing approach 
```

2021-07-13 15:06 UTC, pjgg commented
> I have one final item to cover.
> 
> What if user has defined test resources to start the database. What will happen if the tests are executed, will it collide with DevServices / is there some automagic to detect this?

Well, in the exploratory test that we did, the test is pointing to a SQL init script that is executed at the begging by  hibernate ORM
Properties -> https://github.com/quarkus-qe/quarkus-test-suite/blob/main/sql-db/sql-app/src/test/resources/postgresql.properties#L2

Yes, but is true we should add to our test plan a point that cover "DB evolution" quarkus extensions as Flyway or Liquidbase(TP)

2021-07-15 08:18 UTC, rsvoboda approved these changes
I think it's OK to proceed, the TP can be evolved if we spot new area for coverage as we go.

2021-07-15 08:18 UTC, merged