Tech Preview support for Message tracing and Open Telemetry
quarkus-qe/quarkus-test-plans pull request #36
Opened 2021-09-06 14:04 UTC by kshpak

2021-09-06 16:21 UTC, rsvoboda requested changes

2021-09-06 16:21 UTC, rsvoboda commented on QUARKUS-280.md
> +
Add this text `This feature request is supposed to focus primarily on quarkus-opentelemetry and quarkus-opentelemetry-exporter-jaeger, according to PM they are the demanded by other products.` on new line.

2021-09-06 16:21 UTC, rsvoboda commented on QUARKUS-280.md
> +## Scope of the testing
Our scope of work according the analysis in the rfe is 
AIs for RHBQ 2.2 / QE:
```
    New tests in QE TS to try OpenTelemetry on OpenShift
    Reach equivalent test coverage as for OpenTracing in QE TS
```
Please adjust the TP and link the analysis that I did.

Community side conclusions section says `Community test coverage needs to improve in both Quarkus integration tests and Quarkus Quickstarts (use Jaeger, cover Jaeger exporter, cover Reactive Messaging).`

This effort is for upstream developers, not us. I will create GH issues for these areas as requested by Thomas (https://issues.redhat.com/browse/QUARKUS-280?focusedCommentId=18936836&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18936836  and bellow)

2021-09-06 19:08 UTC, rsvoboda commented on QUARKUS-280.md
> +
Add link to the analysis done on RFE - https://issues.redhat.com/browse/QUARKUS-280?focusedCommentId=18936836&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-18936836

2021-09-07 07:54 UTC, kshpak commented
PR updated

2021-09-07 07:57 UTC, rsvoboda approved these changes

2021-09-07 07:57 UTC, merged