Upgrade JDK17 jenkins jobs references
quarkus-qe/quarkus-test-plans pull request #46
Opened 2022-01-11 16:03 UTC by pjgg

2022-01-11 23:15 UTC, mjurc requested changes

2022-01-11 23:15 UTC, mjurc commented on QUARKUS-728.md
> + That could be reflected in the following Jenkins matrix jobs:
Think the "matrix" part could be omitted - one of the jobs is not matrix, after all :)

2022-01-12 12:27 UTC, rsvoboda requested changes
remove `.idea/.xml files`

2022-01-12 12:34 UTC, mjurc approved these changes
LGTM, thanks for the update

2022-01-12 12:35 UTC, merged

2022-01-12 12:36 UTC, rsvoboda commented
@mjurc you merged unwanted .idea files :/