QUARKUS-1223 Hibernate Search product support
quarkus-qe/quarkus-test-plans pull request #57
Opened 2022-03-02 14:24 UTC by jsmrcka

2022-03-02 15:01 UTC, rsvoboda requested changes
I miss info about impact on execution env and execution time.

OpenShift and development experience topics are not covered well enough.

Are there any extensions combinations that should be checked, does this extension work well with both RESTEasy reactive and classic (upstream tests are using RESTEasy classing for the jaxrs endpoints)?

2022-03-03 09:07 UTC, jsmrcka commented on QUARKUS-1223.md
> +What is missing:
After consultation with Yoann: 
- Multiple PUs are covered in https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-search-orm-elasticsearch/deployment/src/test/java/io/quarkus/hibernate/search/elasticsearch/test/multiplepersistenceunits/MultiplePersistenceUnitsCdiTest.java (I missed that one). We can implement an IT in our TS, but I'm not sure if there would be any added value. 
- `@GenericField` and `Bridges` are not mentioned in the Quarkus guide, along with other features form HSearch. It's not practical to test everything from HSearch, so I propose to omit these features.

2022-03-03 09:12 UTC, jsmrcka commented on QUARKUS-1223.md
> +- Adopt Quarkus integration tests into QE test suite or make sure the integration tests are part of upstream testing pipeline.
My mistake, the upstream ITs are executed, so no need to duplicate them.

2022-03-03 09:37 UTC, jsmrcka commented on QUARKUS-1223.md
> +- Integrate Quickstart (https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-search-orm-elasticsearch-quickstart) into testing pipelines.
Yes. I rephrased it.

2022-03-03 09:38 UTC, jsmrcka commented on QUARKUS-1223.md
> +- Implement test coverage in QE test suite for missing topics (multiple PUS, `@GenericField`, Bridges).
See https://github.com/quarkus-qe/quarkus-test-plans/pull/57#discussion_r818449481.

2022-03-03 09:40 UTC, jsmrcka commented
@rsvoboda PR updated. Changes are in a separate commit, which I will squash after we resolve all issues.

2022-03-03 12:10 UTC, rsvoboda requested changes

2022-03-03 12:10 UTC, rsvoboda commented on QUARKUS-1223.md
> +    - Other supported databases: `jdbc-derby`, `jdbc-mariadb`, `jdbc-mssql`, `jdbc-mysql`, `jdbc-oracle` (module `sql-db/sql-app` might be a good target location).
Please do not mix stuff with `sql-db/sql-app` and create new module. It's says Hibernate Search but it doesn't have too much in common with vanilla Hibernate ORM.

I would pick 2PUs: `jdbc-mariadb` and  `jdbc-oracle`, PostgreSQL is covered in upstream.

2022-03-03 12:10 UTC, rsvoboda commented on QUARKUS-1223.md
> +  - Combination with extensions:
Ideally I would like to have combination of these use-cases: Multiple persistence units ++ Outbox polling ++ Multi-tenancy using separate schema
Ideally all of the combined, but we could end up with 2 of them if there are challenges with it.

2022-03-03 13:22 UTC, rsvoboda commented
Please squash them and I will merge it

2022-03-03 14:25 UTC, rsvoboda approved these changes

2022-03-03 14:25 UTC, merged