Describe test plans for coverage of Qute
quarkus-qe/quarkus-test-plans pull request #92
Opened 2022-09-09 14:34 UTC by fedinskiy

Relevant issues:
https://issues.redhat.com/browse/QUARKUS-2328
https://issues.redhat.com/browse/QUARKUS-2329
https://issues.redhat.com/browse/QUARKUS-2330

2022-09-13 07:04 UTC, rsvoboda requested changes

2022-09-13 07:04 UTC, rsvoboda commented on QUARKUS-2330.md
> +## Automated test development
What's the current estimation for TD?

2022-09-13 10:39 UTC, fedinskiy commented on QUARKUS-2330.md
> +## Automated test development
5-10 days. Added time estimation.

2022-09-13 11:31 UTC, rsvoboda commented on QUARKUS-2330.md
> +18. Content negotiation.
```suggestion
18. Content negotiation
```

2022-09-13 11:32 UTC, rsvoboda commented on QUARKUS-2330.md
> +   10. Eval sections (covered).
```suggestion
   10. eval sections (covered)
```

2022-09-13 11:35 UTC, rsvoboda commented on QUARKUS-2330.md
> +17. Other templates: @TemplateData (covered), @TemplateEnum (covered), @TemplateGlobal (covered), @CheckedTemplate (covered). These are not expected to work in native mode, though
> These are not expected to work in native mode, though

Where is this info tracked?

2022-09-13 12:35 UTC, fedinskiy commented on QUARKUS-2330.md
> +17. Other templates: @TemplateData (covered), @TemplateEnum (covered), @TemplateGlobal (covered), @CheckedTemplate (covered). These are not expected to work in native mode, though
Changed the wording.

2022-09-14 08:47 UTC, mjurc approved these changes
This looks like a good plan to me now, thanks.

2022-09-14 11:15 UTC, merged