QUARKUS-2349 - Fully support Java 17 and drop Java 11 for Native application
quarkus-qe/quarkus-test-plans pull request #94
Opened 2022-09-13 14:10 UTC by pjgg

Fully support Java 17 and drop Java 11 for Native application - Test plan

2022-09-13 19:07 UTC, rsvoboda approved these changes

2022-09-13 19:07 UTC, rsvoboda commented on QUARKUS-2349.md
> +- Native daily GitHub builds will cover GraalVM / Mandrel community JDK17 container images `ubi-quarkus-native-image:22.2-java17` and `ubi-quarkus-mandrel:22.2-java17`
```suggestion
- Native daily GitHub builds will cover GraalVM and Mandrel community JDK17 container images
  - `ubi-quarkus-native-image:22.2-java17` and `ubi-quarkus-mandrel:22.2-java17` now
  - targeting `ubi-quarkus-native-image:22.3-java17` and `ubi-quarkus-mandrel:22.3-java17` (when available) for Quarkus 2.13.z releases
```

2022-09-13 19:07 UTC, rsvoboda approved these changes
Changes are needed

2022-09-13 19:08 UTC, rsvoboda requested changes
Changes are needed

2022-09-14 13:54 UTC, rsvoboda commented on QUARKUS-2349.md
> +
https://issues.redhat.com/browse/QUARKUS-2347 ?

2022-09-14 14:09 UTC, pjgg commented on QUARKUS-2349.md
> +
Yes is this one, I have added a reference directly in the TP

2022-09-14 20:11 UTC, rsvoboda requested changes
Mandrel and GraalVM naming needs to be adjusted

2022-09-14 20:11 UTC, rsvoboda commented on QUARKUS-2349.md
> +- Upstream we run both mandrel and graalvm in some cases, in downstream we use mandrel only
```suggestion
- Upstream we run both Mandrel and GraalVM in some cases, in downstream we use Mandrel only
```

2022-09-14 20:11 UTC, rsvoboda commented on QUARKUS-2349.md
> +- GraalVM/mandrel JDK17 native builder images are going to be used to compile Quarkus native application regardless of whether the application runs on java 11 or 17
```suggestion
- GraalVM/Mandrel JDK17 native builder images are going to be used to compile Quarkus native application regardless of whether the application runs on java 11 or 17
```

2022-09-15 09:43 UTC, rsvoboda approved these changes

2022-09-15 09:43 UTC, merged